name: 'DWH_dbt_project'
version: '1.0.0'

profile: 'DWH_dbt_project'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  # Global hook for all models
  on_run_end:
    - "GRANT USAGE ON SCHEMA {{ target.schema }} TO dwh_northwind_readonly"
    - "GRANT SELECT ON ALL TABLES IN SCHEMA {{ target.schema }} TO dwh_northwind_readonly"
    - "GRANT USAGE ON SCHEMA {{ target.schema }} TO DWH_dbt_project"
    - "GRANT SELECT ON ALL TABLES IN SCHEMA {{ target.schema }} TO DWH_dbt_project"

  DWH_dbt_project:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

